services:
  zookeeper:
    image: zookeeper:3.6.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_HEAP_SIZE: 1024
    volumes:
      - zookeeper_data:/data:delegated
      - zookeeper_log:/datalog:delegated
      - ./zoo.cfg:/conf/zoo.cfg
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'srvr' | nc localhost 2181 | grep 'Zookeeper version'"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1g
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_PREFLIGHT_CHECK_ENABLED: "false"
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data:delegated
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD", "nc", "-z", "kafka", "9092"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 4g
    restart: unless-stopped

volumes:
  portainer_data:
  zookeeper_data:
  zookeeper_log:
  kafka_data:

networks:
  kafka-net:
    driver: bridge